services:
  postgres-server:    
    image: postgres:16
    restart: always
    environment:   
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - /data/share/postgresql:/var/lib/postgresql/data    
    networks:
      my_network:
        ipv4_address: 172.23.0.2
          
        
  zabbix-server:     
    image: zabbix/zabbix-server-pgsql:alpine-7.0.5
    restart: always
    environment:   
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres-server
    ports:
      - 10051:10051    
    volumes:
      - /data/share/zabbix/data:/var/lib/zabbix
      - /data/share/zabbix/snmtraps:/var/lib/zabbix/snmptraps 
      - /data/share/zabbix/export:/var/lib/zabbix/export
    networks:
      my_network:
        ipv4_address: 172.23.0.3     
  zabbix-web:   
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0.5
    restart: always
    environment:  
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - postgres-server
      - zabbix-server
    ports:  
      - 8092:8080
    networks:
      my_network:
        ipv4_address: 172.23.0.4    
  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.0.5
    privileged: true
    restart: always
    ports:
      - 10050:10050
    depends_on:
      - zabbix-server
    networks:
      my_network:
        ipv4_address: 172.23.0.5    
networks:
  my_network:
    ipam:
      config:
        - subnet: 172.23.0.0/24  
      
        

    


